#let labels = (
  de: (
    abstract: "Zusammenfassung",
    abstract_en: "Abstract",
    acknowledgements: "Danksagung",
    appendix: "Anhang",
    bibliography: "Literaturverzeichnis",
    contents: "Inhaltsverzeichnis",
    declaration: "Selbstständigkeitserklärung",
    examiners: "Prüfende",
    keywords: "Schlagwörter",
    list_of_figures: "Abbildungsverzeichnis",
    list_of_tables: "Tabellenverzeichnis",
    list_of_acronyms: "Abkürzungsverzeichnis",
    matriculation_number: "Matrikelnummer",
    supervisors: "Betreuer",
    months: (
      "Januar",
      "Februar",
      "März",
      "April",
      "Mai",
      "Juni",
      "July",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ),
  ),
  en: (
    abstract: "Abstract",
    abstract_en: "Abstract",
    acknowledgements: "Acknowledgements",
    appendix: "Appendix",
    bibliography: "References",
    contents: "Contents",
    declaration: "Declaration of Authorship",
    examiners: "Examiners",
    keywords: "Keywords",
    list_of_figures: "List of Figures",
    list_of_tables: "List of Tables",
    list_of_acronyms: "List of Acronyms",
    matriculation_number: "Student ID",
    supervisors: "Supervisors",
    months: (
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ),
  ),
)
