#let heiti = ("Times New Roman", "Heiti SC", "Heiti TC")
#let songti = ("Times New Roman", "Songti SC", "Songti TC")
#let zhongsong = ("Times New Roman","STZhongsong", "SimSun")
#let kaiti = ("Times New Roman", "Kaiti SC", "Kaiti TC")
#let fangsong = ("Times New Roman", "FangSong_GB2312")